Add sync for multiple shell subprocess

diff --git a/byte-test b/byte-test
--- a/byte-test
+++ b/byte-test
@@ -8,51 +8,95 @@ source "$CURRENT_DIR/byte-com"
 elf=$1
 cnt=$2
 with_compare=$3
+sync1=`mktemp`
+sync2=`mktemp`
 
 run_test() {
-  # echo "Generating..."
-  ./"$elf"_ge > $i.gg
-  #--------------------------------------
-  # echo "Running..."
-  cmd=""$timeout" -s2 "$TIME_LIMITS" ./"$elf" < $i.gg > $i.ga 2>run_err"
+  ./"$elf"_ge > $i.gg 2>run_err
+  #------------------------------------------------------------------------
+  cmd=""$timeout" -s2 "$TIME_LIMITS" ./"$elf" < $1.gg > $1.ga 2>run_err"
   if ! { bash -c "$cmd"; }; then
-    error "\n----------------Run Error---------------------------\n"
-    cat run_err
-    error "\n-----------------------------------------------------\n"
-    # cat $i.gg | tee -a $elf.in
-    exit 1
+    ( flock -x 2
+      if [[ -f "$sync1" ]]; then
+        error "\n\\\\\\-------------------Running error: $1----------------------//"
+        cat run_err
+        error "\n--------------------------------------------------------------"
+        flock -x $elf.in
+        echo " " >> $elf.in
+        cat $1.gg | tee -a $elf.in
+        echo " " >> $elf.in
+        flock -u $elf.in
+        error "\n\\\\\\-----------------------------------------------------//\n"
+        rm -f "$sync2"
+        exit 1
+      fi
+    )2>stderr
   fi
-  #--------------------------------------
+  #---------------------------------------------------------------------
   if [[ "$with_compare" == "1" ]]; then
-    # echo "Comparing..."
-    cmd="./"$elf"_mp < $i.gg > $i.gb 2>compare_error"
+    cmd="./"$elf"_mp < $1.gg > $1.gb 2>compare_error"
     if ! { bash -c "$cmd"; }; then
-      error "\n---------------Compare Error------------------------------\n"
-      cat compare_error
-      error "\n----------------------------------------------------------\n"
-      exit 1
+      ( flock -x 2
+        if [[ -f "$sync1" ]]; then
+          error "\n---------------Running error------------------------------\n"
+          cat compare_error
+          error "\n----------------------------------------------------------\n"
+          rm -f "$sync2"
+          exit 1
+        fi
+      ) 2>stderr
     fi
-    if ! diff -y -W 60 "$i.ga" "$i.gb" 2>&1 >/dev/null; then
-      error "\n----------Different input---------------"
-      cat $i.gg
-      error "\n------------Output------------------------"
-      diff -y -W 60 "$i.ga" "$i.gb"
-      # cat $i.gg | tee -a $elf.in
+    if [[ ! -f "$1.ga" || ! -f "$1.gb" ]]; then
+      ( flock -x 2
+        if [[ -f "$sync1" ]]; then
+          error "\n\\\\------------No file generated to diff-------------------//\n"
+          rm -f "$sync2"
+          exit 1
+        fi
+      ) 2>stderr
+    fi
+    if ! diff -y -W 60 "$1.ga" "$1.gb" 2>&1 >/dev/null; then
+      # NOTE: use flock to sync subprocess.
+      ( flock -x 2
+        if [[ -f "$sync1" ]]; then
+          error "\n\\\\\\-------------------Comparing result $1----------------------//"
+          diff -y -W 60 "$1.ga" "$1.gb"
+          error "---------------------------------------------------------------"
+          flock -x $elf.in
+          echo " " >> $elf.in
+          cat $1.gg | tee -a $elf.in
+          echo " " >> $elf.in
+          flock -u $elf.in
+          error "\n\\\\\\---------------------------------------------------------//\n"
+          rm -f "$sync2"
+          exit 1
+        fi
+      ) 2>stderr
       exit 1
     fi
   fi
-  printf "test...$i \e[1;32m\\t\\t\\t PASS\e[m\n"
+  ( flock -x 2
+    printf "test...$1 \e[1;32m\\t\\t\\t PASS\e[m\n"
+  ) 2>stderr
 }
 
-clean () {
-  rm -f *.gg *.ga *.gb
-  rm -f compare_error
-  rm -f run_err
+trap cleanup 1 2 3 6 9
+
+cleanup() {
+  rm -f "$sync1"
+  wait
+  rm -f *.gg *.ga *.gb compare_error run_err stderr
+  exit 1
 }
 
-clean
+rm -f *.gg *.ga *.gb compare_error run_err stderr
 for i in $(seq 1 "$cnt"); do
-  (run_test) &
+  (run_test $i) &
+
   if (( $i % 4 == 0 )); then wait; fi
+
+  if [[ ! -f "$sync2" ]]; then
+    kill -SIGINT $$
+  fi
 done
-clean
+rm -f *.gg *.ga *.gb compare_error run_err stderr
